default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("POSTGRES_HOST") { "postgres" } %>
  username: <%= ENV.fetch("POSTGRES_USER") { "postgres" } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { "postgres" } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

test:
  <<: *default
  database: matestack_ui_test

development:
  <<: *default
  database: matestack_ui_development

staging:
  <<: *default
  database: matestack_ui_staging

production:
  <<: *default
  database: matestack_ui_production
